name: build
on:
  workflow_dispatch:
  push:
    paths:
      - '**.dts'
      - '**Makefile'
  pull_request:
    paths:
      - '**.dts'
      - '**Makefile'
  merge_group:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [linux-rockchip, linux-rk356x, linux-stable]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends device-tree-compiler
          sudo dpkg --add-architecture arm64
          case "${{ matrix.version }}" in
            linux-rockchip)
              wget https://github.com/radxa-pkg/linux-rockchip/releases/download/5.10.110-11/linux-headers-5.10.110-11-rockchip_5.10.110-11-8c4e8d205_arm64.deb
              sudo apt install ./linux-headers-5.10.110-11-rockchip_5.10.110-11-8c4e8d205_arm64.deb
              ;;
            linux-rk356x)
              wget https://github.com/radxa-pkg/linux-rk356x/releases/download/5.10.160-7/linux-headers-5.10.160-7-rk356x_5.10.160-7-fc20e0bcd_arm64.deb
              sudo apt install ./linux-headers-5.10.160-7-rk356x_5.10.160-7-fc20e0bcd_arm64.deb
              ;;
          esac
      - name: Build
        run: |
          case "${{ matrix.version }}" in
            linux-stable)
              make -j$(nproc)
              ;;
            linux-rockchip)
              make -j$(nproc) KERNEL_HEADER_VERSION=5.10.110-11-rockchip CONFIG_ARCH_MESON=n CONFIG_CPU_RK3399=rockchip CONFIG_CPU_RK3568=rockchip CONFIG_CPU_RK3588=rockchip
              ;;
            linux-rk356x)
              make -j$(nproc) KERNEL_HEADER_VERSION=5.10.160-7-rk356x CONFIG_ARCH_MESON=n CONFIG_CPU_RK3399=rockchip CONFIG_CPU_RK3568=rockchip CONFIG_CPU_RK3588=rockchip
              ;;
          esac
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.version }}
          path: |
            arch/**/*.dtbo