name: Build
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          make -j$(nproc)
